### ISSUE TITLE
Differences to helmfile?

### ISSUE THREAD

**Issue by tyrken** [Traackr/binnacle#13]
It's interesting that this project seems similar to & perhaps was inspired by `helmfile` but still exists.  What differences (other than boring syntactical ones) exist between the two projects?  Why should one choose one over the other?

Sorry for opening this as an issue - would have used a Discussion if you had them turned on.  Feel free to close it, though it would be nice to expand on this in the README/add a FAQ section.

**Comment by jmmk** [comment]
`Helmfile` can do everything that binnacle can do and more. It is more powerful and more flexible, but it comes with a cost of being more complex. 

`binnacle` is a simple Helm wrapper that allows specifying a Helm chart and the values that will be used to create a release. 

It still exists because we use it internally to define all of our releases, and we haven't had a compelling reason to switch to another tool like [helmfile](https://github.com/roboll/helmfile) or [flux](https://fluxcd.io/), though we are keeping an eye on the ecosystem to see if there are tools that can better suit our needs.

**Comment by tyrken** [comment]
Cool thanks for explaining
